import java.awt.*;
import java.awt.image.BufferedImage;
import java.util.*;
import javax.swing.JColorChooser;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class NewJFrame extends javax.swing.JFrame {
    Color brushColor = Color.black;
    int old_mouse_x = 0;
    int old_mouse_y = 0;
    Graphics2D grafika;
    Graphics2D previewgrafika;
    boolean draw_figure = false;
    int first_mouse_x = 0;
    int first_mouse_y = 0;
    int old_width = 0;
    int old_height = 0;
    int old_evtx = 0;
    int old_evty = 0;
    BufferedImage canvas, canvas_preview;


    ArrayList<Integer> ListX = new ArrayList<Integer>();
    ArrayList<Integer> ListY = new ArrayList<Integer>();
    int n = 0;

    /**
     * Creates new form NewJFrame
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        preview = new DrawingPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ToolsLabel2 = new javax.swing.JLabel();
        ToolsLabel3 = new javax.swing.JLabel();
        Tools = new javax.swing.JComboBox<>();
        Width = new javax.swing.JComboBox<>();
        ColorButton = new javax.swing.JButton();
        ColorField = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        Save = new javax.swing.JButton();  // NOWOŚĆ: Przycisk Zapisz
        Load = new javax.swing.JButton();   // NOWOŚĆ: Przycisk Importuj

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        preview.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout previewLayout = new javax.swing.GroupLayout(preview);
        preview.setLayout(previewLayout);
        previewLayout.setHorizontalGroup(
                previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        previewLayout.setVerticalGroup(
                previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 513, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(preview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(preview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        ToolsLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ToolsLabel2.setText("Narzędzia");

        ToolsLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ToolsLabel3.setText("Grubość Lini");

        Tools.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tools.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ołówek", "Prostokąt", "Linia", "Okrąg", "Wielokąt" }));

        Width.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Width.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1px", "2px", "3px", "4px", "5px" }));
        Width.setLightWeightPopupEnabled(false);
        Width.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WidthActionPerformed(evt);
            }
        });

        ColorButton.setText("Kolor");
        ColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorButtonActionPerformed(evt);
            }
        });

        ColorField.setEditable(false);
        ColorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorFieldActionPerformed(evt);
            }
        });

        Clear.setText("Wyczyść");
        Clear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        // NOWOŚĆ: Inicjalizacja nowych przycisków
        Save.setText("Zapisz");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);  // Pusty – tu dodasz kod zapisywania
            }
        });

        Load.setText("Importuj");
        Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadActionPerformed(evt);  // Pusty – tu dodasz kod importowania
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Tools, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ToolsLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(Width, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(ColorButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(ColorField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(ToolsLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)  // ZMiana: Zmniejszone z 421, żeby było miejsce
                                .addComponent(Clear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)  // NOWOŚĆ: Mała przerwa
                                .addComponent(Save)  // NOWOŚĆ: Dodany przycisk Zapisz
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)  // NOWOŚĆ: Mała przerwa
                                .addComponent(Load)  // NOWOŚĆ: Dodany przycisk Importuj
                                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ToolsLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ToolsLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(7, 7, 7)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(Tools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Width, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(ColorButton)
                                                                .addComponent(ColorField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)  // NOWOŚĆ: Wyrównanie nowych przycisków z Clear
                                                        .addComponent(Clear)
                                                        .addComponent(Save)
                                                        .addComponent(Load))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-E
    public NewJFrame() {
        initComponents();
        int width = jPanel1.getWidth();
        int height = jPanel1.getHeight();
        System.out.println(width);
        System.out.println(height);
        canvas = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        canvas_preview = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        grafika = (Graphics2D) canvas.createGraphics();
        previewgrafika = (Graphics2D) canvas_preview.createGraphics();
        grafika.setColor(Color.WHITE);
        grafika.fillRect(0, 0, width, height);
        grafika.setColor(brushColor);
    }
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        grafika.setColor(Color.WHITE);
        grafika.fillRect(0, 0, canvas.getWidth(), canvas.getHeight());
        grafika.setColor(brushColor);
        preview.repaint();
    }//GEN-LAST:event_ClearActionPerformed

    private void ColorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorFieldActionPerformed

    private void ColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorButtonActionPerformed
        brushColor = JColorChooser.showDialog(null, "Wybierz kolor", brushColor);
        ColorField.setBackground(brushColor);
    }//GEN-LAST:event_ColorButtonActionPerformed

    private void WidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WidthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WidthActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        old_mouse_x = evt.getX();
        old_mouse_y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        if(Tools.getSelectedIndex()==0){
            grafika = (Graphics2D)canvas.createGraphics();
            if(grafika != null){
                grafika.setColor(brushColor);
                grafika.setStroke(new BasicStroke(Width.getSelectedIndex()+1));
                grafika.drawLine(old_mouse_x, old_mouse_y, evt.getX(), evt.getY());
                preview.repaint();
            }
            old_mouse_x = evt.getX();
            old_mouse_y = evt.getY();
        }
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {
        if(Tools.getSelectedIndex()>0 && draw_figure == false){
            draw_figure = true;
            first_mouse_x  = old_mouse_x;
            first_mouse_y = old_mouse_y;
            old_width=0;
            old_height=0;

        }else if(Tools.getSelectedIndex()>0 && Tools.getSelectedIndex() != 4 && draw_figure == true) {

            draw_figure =  false;
        }
        int radius = 3;
        if(Tools.getSelectedIndex()==4){
            grafika = (Graphics2D)canvas.createGraphics();

            ListX.add(evt.getX());
            ListY.add(evt.getY());
            grafika.fillOval(evt.getX()- radius, evt.getY() - radius, 2*radius, 2*radius);
            preview.repaint();
            if(ListX.size() >2 && evt.getX() > (ListX.get(0) - 20)&& evt.getX() < (ListX.get(0) + 20) && evt.getY() > (ListY.get(0) - 20)&& evt.getY() < (ListY.get(0) + 20) ){
                int size = ListX.size();
                ListX.remove(size-1);
                ListY.remove(size-1);
                ListX.add(ListX.get(0));
                ListY.add(ListY.get(0));

                int[] arrayx = new int[ListX.size()];
                for (int i = 0; i < ListX.size(); i++) {
                    arrayx[i] = ListX.get(i);
                }
                int[] arrayy = new int[ListY.size()];
                for (int i = 0; i < ListY.size(); i++) {
                    arrayy[i] = ListY.get(i);
                }

                grafika.setColor(brushColor);
                grafika.fillPolygon(arrayx, arrayy, arrayy.length);
                preview.repaint();

                ListX.clear();
                ListY.clear();
                draw_figure = false;
            }
            first_mouse_x =  evt.getX();
            first_mouse_y =  evt.getY();

        }

    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {
        if (draw_figure == true){
            int a;
            int b;
            if(first_mouse_x < evt.getX()){
                a = first_mouse_x;

            }else {
                a  = evt.getX();
            }
            if (first_mouse_y < evt.getY()){
                b = first_mouse_y;
            }else  {
                b = evt.getY();
            }

            int width = evt.getX() - a;
            int height  = evt.getY()  - b;

            grafika = (Graphics2D)canvas.createGraphics();
            previewgrafika = (Graphics2D) canvas_preview.createGraphics();

            if (Tools.getSelectedIndex() == 1)
            {

                grafika.setColor(Color.WHITE);
                grafika.fillRect(first_mouse_x, first_mouse_y, old_width, old_height);
                preview.repaint();
                grafika.setColor(brushColor);
                grafika.fillRect(first_mouse_x, first_mouse_y, width, height);
                preview.repaint();
            }
            if (Tools.getSelectedIndex() == 3)
            {
                grafika.setColor(Color.WHITE);
                grafika.fillOval(first_mouse_x, first_mouse_y, old_width, old_height);
                preview.repaint();
                grafika.setColor(brushColor);
                grafika.fillOval(first_mouse_x, first_mouse_y, width, height);
                preview.repaint();

            }
            if (Tools.getSelectedIndex() == 2)
            {
                grafika.setStroke(new BasicStroke(Width.getSelectedIndex()+1));
                grafika.setColor(Color.WHITE);
                grafika.drawLine(first_mouse_x, first_mouse_y, old_evtx, old_evty);
                preview.repaint();
                grafika.setColor(brushColor);
                grafika.drawLine(first_mouse_x, first_mouse_y, evt.getX(), evt.getY());
                preview.repaint();

            }
            if (Tools.getSelectedIndex() == 4)
            {

                grafika.setColor(Color.WHITE);
                grafika.drawLine(first_mouse_x, first_mouse_y, old_evtx, old_evty);
                preview.repaint();
                grafika.setColor(brushColor);
                grafika.drawLine(first_mouse_x, first_mouse_y, evt.getX(), evt.getY());
                preview.repaint();

            }
            old_width = width;
            old_evtx = evt.getX();
            old_evty = evt.getY();
            old_height = height;

        }
    }//GEN-LAST:event_jPanel1MouseMoved

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            if (!selectedFile.getName().endsWith(".png")) {
                selectedFile = new File(selectedFile.getAbsolutePath() + ".png");
            }
            try {
                ImageIO.write(canvas, "png", selectedFile);

            } catch (java.io.IOException ex){

            }



        }
    }

    private void LoadActionPerformed(java.awt.event.ActionEvent evt) {

            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Obrazy (PNG, JPG)", "png", "jpg"));
            int result = fileChooser.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File selectedFile = fileChooser.getSelectedFile();
                try {
                    BufferedImage loadedImage = ImageIO.read(selectedFile);
                    if (loadedImage == null) {
                        return;
                    }
                    grafika.setColor(Color.WHITE);
                    grafika.fillRect(0, 0, canvas.getWidth(), canvas.getHeight());
                    grafika.drawImage(loadedImage, 0, 0, canvas.getWidth(), canvas.getHeight(), null);
                    preview.repaint();
               } catch (java.io.IOException ex) {
               }

        }
    }

    private class DrawingPanel extends javax.swing.JPanel {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (canvas != null) {
                g.drawImage(canvas, 0, 0, null);
            }
            if (canvas_preview != null) {
                g.drawImage(canvas_preview, 0, 0, this);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton ColorButton;
    private javax.swing.JTextField ColorField;
    private javax.swing.JComboBox<String> Tools;
    private javax.swing.JLabel ToolsLabel2;
    private javax.swing.JLabel ToolsLabel3;
    private javax.swing.JComboBox<String> Width;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel preview;
    private javax.swing.JButton Save;
    private javax.swing.JButton Load;
    // End of variables declaration//GEN-END:variables
}